// This file is "main.dart"
// ignore_for_file: non_constant_identifier_names, depend_on_referenced_packages

import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user_info.freezed.dart';
// optional: Since our UserInfo class is serializable, we must add this line.
// But if UserInfo was not serializable, we could skip it.
part 'user_info.g.dart';

@freezed
class UserInfo with _$UserInfo {
  const factory UserInfo({
    int? id,
    int? expert_id,
    String? avatar,
    String? username,
    String? email,
    String? phone_number,
    int? status,
    int? is_professional_request,
    int? gender,
    int? age,
    int? mood,
    int? sleep,
    int? stress,
    int? role,
    String? email_verified_at,
  }) = _UserInfo;
  factory UserInfo.fromJson(Map<String, dynamic> json) =>
      _$UserInfoFromJson(json);
}
