// This file is "main.dart"
// ignore_for_file: non_constant_identifier_names, depend_on_referenced_packages

import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'expert_info.freezed.dart';
// optional: Since our ExpertInfo class is serializable, we must add this line.
// But if ExpertInfo was not serializable, we could skip it.
part 'expert_info.g.dart';

@freezed
class ExpertInfo with _$ExpertInfo {
  const factory ExpertInfo({
    int? id,
    String? name,
    int? specialization,
    String? bio,
    String? contact_info,
    String? phone_number,
    String? avatar,
    String? specialization_string,
  }) = _ExpertInfo;
  factory ExpertInfo.fromJson(Map<String, Object?> json) =>
      _$ExpertInfoFromJson(json);
}
