// This file is "main.dart"
// ignore_for_file: non_constant_identifier_names, depend_on_referenced_packages

import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'create_post_params.freezed.dart';
// optional: Since our CreatePostParams class is serializable, we must add this line.
// But if CreatePostParams was not serializable, we could skip it.
part 'create_post_params.g.dart';

@freezed
class CreatePostParams with _$CreatePostParams {
  const factory CreatePostParams({
    String? title,
    String? content,
    int? forum_id,
  }) = _CreatePostParams;
  factory CreatePostParams.fromJson(Map<String, Object?> json) =>
      _$CreatePostParamsFromJson(json);
}
