// This file is "main.dart"
// ignore_for_file: non_constant_identifier_names, depend_on_referenced_packages

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:intl/intl.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'post_info.freezed.dart';
// optional: Since our PostInfo class is serializable, we must add this line.
// But if PostInfo was not serializable, we could skip it.
part 'post_info.g.dart';

@freezed
class PostInfo with _$PostInfo {
  const factory PostInfo({
    int? id,
    int? forum_id,
    int? user_id,
    String? username,
    int? like_count,
    int? comment_count,
    String? content,
    String? title,
    String? post_created_at,
  }) = _PostInfo;
  factory PostInfo.fromJson(Map<String, Object?> json) =>
      _$PostInfoFromJson(json);
}

extension PostInfoExtensions on PostInfo {
  String get formattedCreatedAt {
    if (post_created_at == null || post_created_at!.isEmpty) {
      return "";
    }
    try {
      final DateTime dateTime = DateTime.parse(post_created_at!);
      return DateFormat('yyyy-MM-dd HH:mm:ss').format(dateTime);
    } catch (e) {
      return "Invalid Date";
    }
  }
}
