// This file is "main.dart"
// ignore_for_file: non_constant_identifier_names, depend_on_referenced_packages

import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'exercise_info.freezed.dart';
// optional: Since our ExerciseInfo class is serializable, we must add this line.
// But if ExerciseInfo was not serializable, we could skip it.
part 'exercise_info.g.dart';

@freezed
class ExerciseInfo with _$ExerciseInfo {
  const factory ExerciseInfo({
    int? id,
    String? title,
    String? description,
    int? type,
    String? content,
    String? media_url,
    String? thumbnail_url,
    String? type_string,
  }) = _ExerciseInfo;
  factory ExerciseInfo.fromJson(Map<String, Object?> json) =>
      _$ExerciseInfoFromJson(json);
}
