// This file is "main.dart"
// ignore_for_file: non_constant_identifier_names, depend_on_referenced_packages

import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'chat_expert_info.freezed.dart';
// optional: Since our ChatExpertInfo class is serializable, we must add this line.
// But if ChatExpertInfo was not serializable, we could skip it.
part 'chat_expert_info.g.dart';

@freezed
class ChatExpertInfo with _$ChatExpertInfo {
  const factory ChatExpertInfo({
    int? id,
    int? chat_id,
    int? sender_id,
    int? receiver_id,
    String? message,
    String? sender,
    String? receiver,
    String? created_at,
    String? latest_message,
  }) = _ChatExpertInfo;
  factory ChatExpertInfo.fromJson(Map<String, Object?> json) =>
      _$ChatExpertInfoFromJson(json);
}
