// This file is "main.dart"
// ignore_for_file: non_constant_identifier_names, depend_on_referenced_packages

import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'forum_info.freezed.dart';
// optional: Since our ForumInfo class is serializable, we must add this line.
// But if ForumInfo was not serializable, we could skip it.
part 'forum_info.g.dart';

@freezed
class ForumInfo with _$ForumInfo {
  const factory ForumInfo({
    int? id,
    String? title,
    String? description,
    String? cover_image,
    int? member_count,
    int? post_count,
    int? created_user_id,
    String? created_user_name,
    int? is_joined,
  }) = _ForumInfo;
  factory ForumInfo.fromJson(Map<String, Object?> json) =>
      _$ForumInfoFromJson(json);
}
