// This file is "main.dart"
// ignore_for_file: non_constant_identifier_names, depend_on_referenced_packages

import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'mood_info.freezed.dart';
// optional: Since our MoodInfo class is serializable, we must add this line.
// But if MoodInfo was not serializable, we could skip it.
part 'mood_info.g.dart';

@freezed
class MoodInfo with _$MoodInfo {
  const factory MoodInfo({
    int? id,
    int? user_id,
    String? username,
    String? note,
    String? date,
  }) = _MoodInfo;
  factory MoodInfo.fromJson(Map<String, Object?> json) =>
      _$MoodInfoFromJson(json);
}
