// This file is "main.dart"
// ignore_for_file: non_constant_identifier_names, depend_on_referenced_packages

import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'room_create_params.freezed.dart';
// optional: Since our RoomCreateParams class is serializable, we must add this line.
// But if RoomCreateParams was not serializable, we could skip it.
part 'room_create_params.g.dart';

@freezed
class RoomCreateParams with _$RoomCreateParams {
  const factory RoomCreateParams({
    int? expert_id,
  }) = _RoomCreateParams;
  factory RoomCreateParams.fromJson(Map<String, Object?> json) =>
      _$RoomCreateParamsFromJson(json);
}
