// This file is "main.dart"
// ignore_for_file: non_constant_identifier_names, depend_on_referenced_packages

import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'sign_in_params.freezed.dart';
// optional: Since our SignInParams class is serializable, we must add this line.
// But if SignInParams was not serializable, we could skip it.
part 'sign_in_params.g.dart';

@freezed
class SignInParams with _$SignInParams {
  const factory SignInParams({
    String? identifier,
    String? password,
    int? role,
  }) = _SignInParams;
  factory SignInParams.fromJson(Map<String, Object?> json) =>
      _$SignInParamsFromJson(json);
}
