// This file is "main.dart"
// ignore_for_file: non_constant_identifier_names, depend_on_referenced_packages

import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'sign_up_params.freezed.dart';
// optional: Since our SignUpParams class is serializable, we must add this line.
// But if SignUpParams was not serializable, we could skip it.
part 'sign_up_params.g.dart';

@freezed
class SignUpParams with _$SignUpParams {
  const factory SignUpParams({
    String? identifier,
    String? password,
    String? confirm_password,
    String? username,
  }) = _SignUpParams;
  factory SignUpParams.fromJson(Map<String, Object?> json) =>
      _$SignUpParamsFromJson(json);
}
