// This file is "main.dart"
// ignore_for_file: non_constant_identifier_names, depend_on_referenced_packages

import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user_update_params.freezed.dart';
// optional: Since our UserUpdateParams class is serializable, we must add this line.
// But if UserUpdateParams was not serializable, we could skip it.
part 'user_update_params.g.dart';

@freezed
class UserUpdateParams with _$UserUpdateParams {
  const factory UserUpdateParams({
    int? id,
    String? username,
    String? password,
    String? avatar,
    int? gender,
    int? age,
    int? mood,
    int? sleep,
    int? stress,
    int? is_professional_request,
  }) = _UserUpdateParams;
  factory UserUpdateParams.fromJson(Map<String, Object?> json) =>
      _$UserUpdateParamsFromJson(json);
}
