// This file is "main.dart"
// ignore_for_file: non_constant_identifier_names, depend_on_referenced_packages

import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'chatbot_info.freezed.dart';
// optional: Since our ChatbotInfo class is serializable, we must add this line.
// But if ChatbotInfo was not serializable, we could skip it.
part 'chatbot_info.g.dart';

@freezed
class ChatbotInfo with _$ChatbotInfo {
  const factory ChatbotInfo({
    String? user_message,
    String? bot_reply,
  }) = _ChatbotInfo;
  factory ChatbotInfo.fromJson(Map<String, Object?> json) =>
      _$ChatbotInfoFromJson(json);
}
