// This file is "main.dart"
// ignore_for_file: non_constant_identifier_names, depend_on_referenced_packages

import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'set_mood_params.freezed.dart';
// optional: Since our SetMoodParams class is serializable, we must add this line.
// But if SetMoodParams was not serializable, we could skip it.
part 'set_mood_params.g.dart';

@freezed
class SetMoodParams with _$SetMoodParams {
  const factory SetMoodParams({
    String? mood,
  }) = _SetMoodParams;
  factory SetMoodParams.fromJson(Map<String, Object?> json) =>
      _$SetMoodParamsFromJson(json);
}
